- uses: actions/checkout@v2
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
- name: Log in to container registry
  uses: docker/login-action@v2
  with:
    registry: https://index.docker.io/v1/
    username: ${{}}
    password: ${{}}
    
- name: Build and push container image to registry
  uses: docker/build-push-action@v3
  with:
    context: .
    push: true
    tags: index.docker.io/${{}}/hrb1989/javasp1:${{ github.sha }}
    file: ./Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
    name: 'production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  steps:
  - name: Deploy to Azure Web App
    id: deploy-to-webapp
    uses: azure/webapps-deploy@v2
    with:
    app-name: 'shell7SB1'
    slot-name: 'production'
    publish-profile: ${{}}
    images: 'index.docker.io/${{}}/hrb1989/javasp1:${{ github.sha }}
